version: '3.8'

services:
  db:
    image: postgres:13
    container_name: learning_record_db
    environment:
      POSTGRES_DB: learning_record_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: